name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create environment file
      run: |
        # 환경 변수 설정 (비어있으면 빈 문자열로 설정)
        echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL || '' }}" >> .env.local
        echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY || '' }}" >> .env.local
        echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY || '' }}" >> .env.local
        echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY || '' }}" >> .env.local
        echo "NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL || 'https://faddit-mine-jay-1346s-projects.vercel.app' }}" >> .env.local
        echo "NODE_ENV=production" >> .env.local
        
        # 환경 변수 확인 (값은 숨김)
        echo "Environment variables check:"
        echo "SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL != '' && 'SET' || 'NOT SET' }}"
        echo "SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY != '' && 'SET' || 'NOT SET' }}"
        echo "CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY != '' && 'SET' || 'NOT SET' }}"
        echo "CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY != '' && 'SET' || 'NOT SET' }}"
        echo "APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL != '' && 'SET' || 'NOT SET' }}"
      
    - name: Run linting
      run: npm run lint
      
    - name: Build application
      run: npm run build
      
    - name: Run tests (if available)
      run: npm test --if-present
      
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create environment file
      run: |
        # 환경 변수 설정 (비어있으면 빈 문자열로 설정)
        echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL || '' }}" >> .env.local
        echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY || '' }}" >> .env.local
        echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY || '' }}" >> .env.local
        echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY || '' }}" >> .env.local
        echo "NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL || 'https://faddit-mine-jay-1346s-projects.vercel.app' }}" >> .env.local
        echo "NODE_ENV=production" >> .env.local
        
        # 환경 변수 확인 (값은 숨김)
        echo "Environment variables check:"
        echo "SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL != '' && 'SET' || 'NOT SET' }}"
        echo "SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY != '' && 'SET' || 'NOT SET' }}"
        echo "CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY != '' && 'SET' || 'NOT SET' }}"
        echo "CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY != '' && 'SET' || 'NOT SET' }}"
        echo "APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL != '' && 'SET' || 'NOT SET' }}"
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod' 